# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(479, 399)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_line = QtWidgets.QLineEdit(self.centralwidget)
        self.search_line.setObjectName("search_line")
        self.horizontalLayout.addWidget(self.search_line)
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout.addWidget(self.search_button)
        self.discharge_button = QtWidgets.QPushButton(self.centralwidget)
        self.discharge_button.setObjectName("discharge_button")
        self.horizontalLayout.addWidget(self.discharge_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.notes_list = QtWidgets.QListWidget(self.centralwidget)
        self.notes_list.setObjectName("notes_list")
        self.horizontalLayout_3.addWidget(self.notes_list)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.new_note_button = QtWidgets.QPushButton(self.centralwidget)
        self.new_note_button.setObjectName("new_note_button")
        self.verticalLayout_2.addWidget(self.new_note_button)
        self.edit_note_button = QtWidgets.QPushButton(self.centralwidget)
        self.edit_note_button.setObjectName("edit_note_button")
        self.verticalLayout_2.addWidget(self.edit_note_button)
        self.delete_note_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_note_button.setObjectName("delete_note_button")
        self.verticalLayout_2.addWidget(self.delete_note_button)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.user_change_button = QtWidgets.QPushButton(self.centralwidget)
        self.user_change_button.setObjectName("user_change_button")
        self.horizontalLayout_2.addWidget(self.user_change_button)
        self.export_button = QtWidgets.QPushButton(self.centralwidget)
        self.export_button.setObjectName("export_button")
        self.horizontalLayout_2.addWidget(self.export_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 479, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Notes"))
        self.search_button.setText(_translate("MainWindow", "Поиск"))
        self.discharge_button.setText(_translate("MainWindow", "Сброс"))
        self.new_note_button.setText(_translate("MainWindow", "Новая заметка"))
        self.edit_note_button.setText(_translate("MainWindow", "Редактировать"))
        self.delete_note_button.setText(_translate("MainWindow", "Удалить"))
        self.user_change_button.setText(_translate("MainWindow", "Сменить пользователя"))
        self.export_button.setText(_translate("MainWindow", "Экспортировать"))
