# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_user_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_user_window(object):
    def setupUi(self, new_user_window):
        new_user_window.setObjectName("new_user_window")
        new_user_window.resize(372, 124)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(new_user_window)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.new_user_message = QtWidgets.QLabel(new_user_window)
        self.new_user_message.setObjectName("new_user_message")
        self.horizontalLayout.addWidget(self.new_user_message)
        self.new_user_name = QtWidgets.QLineEdit(new_user_window)
        self.new_user_name.setObjectName("new_user_name")
        self.horizontalLayout.addWidget(self.new_user_name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.error_message = QtWidgets.QLabel(new_user_window)
        self.error_message.setText("")
        self.error_message.setTextFormat(QtCore.Qt.RichText)
        self.error_message.setAlignment(QtCore.Qt.AlignCenter)
        self.error_message.setObjectName("error_message")
        self.verticalLayout.addWidget(self.error_message)
        self.buttonBox = QtWidgets.QDialogButtonBox(new_user_window)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(new_user_window)
        QtCore.QMetaObject.connectSlotsByName(new_user_window)

    def retranslateUi(self, new_user_window):
        _translate = QtCore.QCoreApplication.translate
        new_user_window.setWindowTitle(_translate("new_user_window", "Создание нового пользователя"))
        self.new_user_message.setText(_translate("new_user_window", "Введите имя"))
