# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'note.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(458, 355)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title_message = QtWidgets.QLabel(Form)
        self.title_message.setObjectName("title_message")
        self.horizontalLayout.addWidget(self.title_message)
        self.title_line = QtWidgets.QLineEdit(Form)
        self.title_line.setObjectName("title_line")
        self.horizontalLayout.addWidget(self.title_line)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.note_textedit = QtWidgets.QTextEdit(Form)
        self.note_textedit.setObjectName("note_textedit")
        self.verticalLayout_2.addWidget(self.note_textedit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.save_button = QtWidgets.QPushButton(Form)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_2.addWidget(self.save_button)
        self.cancel_button = QtWidgets.QPushButton(Form)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_2.addWidget(self.cancel_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Новая заметка"))
        self.title_message.setText(_translate("Form", "Заголовок"))
        self.save_button.setText(_translate("Form", "Сохранить"))
        self.cancel_button.setText(_translate("Form", "Отмена"))
